### ISSUE TITLE
what is the usage scenario of this package

### ISSUE THREAD

**Issue by nifflin** [sudo-suhas/symcrypto#1]
thank you for sharing.

The encrypted string can be decrypted only by using the `Crypter` instance which was used to encrypt it. So what is the usage scenario of this package?

**Comment by sudo-suhas** [comment]
We used it to encrypt the order ID which the consumer later used in the URL. Something like `/orders/:encryptedOrderID`. This ensured that the order ID was protected and it would be very unlikely that a malicious user could guess them. 
That said, you should probably look at [tink](https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md) since I am no expert on security.
